{{- if .Values.bot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freqtrade
spec:
  selector:
    matchLabels:
      app: freqtrade
  template:
    metadata:
      labels:
        app: freqtrade
    spec:
      containers:
      - name: freqtrade
        image: {{ .Values.image.image }}:{{ .Values.image.tag }}
        command:
        - freqtrade
        args:
        - trade
        - --config
        - /freqtrade/config/config.json
        - --strategy
        - {{ .Values.bot.strategy_name }}
        - --db-url
        - sqlite:////sqlite/tradesv3.sqlite
        volumeMounts:
        - mountPath: /freqtrade/config
          name: config
        - mountPath: /sqlite
          name: sqlite
        {{- if .Values.bot.volumeMounts }}
        {{- range $_, $vol := .Values.bot.volumeMounts }}
        - name: {{ $vol.name }}
          mountPath: {{ $vol.mountPath }}
        {{- end }}
        {{- else }}
        - mountPath: /freqtrade/user_data/strategies
          name: strategies
        {{- end }}
        ports:
        - name: api
          containerPort: 8080
        {{- if .Values.bot.resources }}
        resources: {{ toYaml .Values.bot.resources | nindent 12 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: freqtrade-config
      - name: sqlite
        persistentVolumeClaim:
          claimName: freqtrade-sqlite
      {{- if .Values.bot.volumes }}
      {{- range $_, $vol := .Values.bot.volumes }}
      - name: {{ $vol.name }}
        hostPath:
          path: {{ $vol.hostPath.path }}
          type: {{ $vol.hostPath.type }}
      {{- else }}
      - name: strategies
        configMap:
          name: freqtrade-strategies
      {{- end }}
      {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freqtrade-sqlite
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bot.pvc_size }}
{{- end }}