{{- if .Values.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: freqtrade
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      {{- if (and .Values.bot.enabled .Values.config.api_server.enabled) }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: freqtrade
            port:
              number: 8080
      {{- end }}
      {{- if (and .Values.backtesting.enabled .Values.backtesting.results.enable_export .Values.backtesting.results.reader_enabled) }}
      - path: /results
        pathType: Prefix
        backend:
          service:
            name: results-reader
            port:
              number: 80
      {{- end }}
---
{{- end }}