config:
  max_open_trades: -1
  stake_currency: BTC
  stake_amount: 1
  tradable_balance_ratio: 0.99
  fiat_display_currency: USD
  timeframe: 5m
  dry_run: true
  cancel_open_orders_on_exit: false
  unfilledtimeout:
    entry: 10
    exit: 10
    exit_timeout_count: 0
    unit: "minutes"
  entry_pricing:
    price_side: "same"
    use_order_book: true
    order_book_top: 1
    price_last_balance: 0.0
    check_depth_of_market:
      enabled: false
      bids_to_ask_delta: 1
  exit_pricing:
    price_side: "same"
    use_order_book: true
    order_book_top: 1
  exchange:
    name: kraken
    key: ''
    secret: ''
    ccxt_config:
      enableRateLimit: true
      rateLimit: 3100
    ccxt_async_config:
      enableRateLimit: true
      rateLimit: 3100
    pair_whitelist: []
    pair_blacklist: []
  pairlists:
  - method: StaticPairList
  edge:
    enabled: false
    process_throttle_secs: 3600
    calculate_since_number_of_days: 7
    allowed_risk: 0.01
    stoploss_range_min: -0.01
    stoploss_range_max: -0.1
    stoploss_range_step: -0.01
    minimum_winrate: 0.60
    minimum_expectancy: 0.20
    min_trade_number: 10
    max_trade_duration_minute: 1440
    remove_pumps: false
  telegram:
    enabled: false
    token: ''
    chat_id: ''
  api_server:
    enabled: false
    listen_ip_address: 0.0.0.0
    listen_port: 8080
    username: admin
    password: secret123
  bot_name: freqtrade
  initial_state: running
  force_entry_enable: false
  internals:
    process_throttle_secs: 5

image:
  image: freqtradeorg/freqtrade
  tag: latest

backtesting:
  enabled: false
  download_data: true
  timerange:
  timeframes: 5m
  strategy_list: SampleStrategy
  fee:
  pvc_size: 1Gi
  results:
    enable_export: true
    reader_enabled: true
    pvc_size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256M
    limits:
      cpu: 100m
      memory: 256M

bot:
  enabled: false
  strategy_name: SampleStrategy
  pvc_size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256M
    limits:
      cpu: 100m
      memory: 256M
  volumeMounts: []
  volumes: []
  verbosity: info

ingress:
  enabled: false
  annotations: {}
  apiVersion: "networking.k8s.io/v1"
  className: ""
  host: "localhost"
  tls:
    enabled: false
    secretName: "freqtrade-tls"

create_config_configmap: true
create_strategies_configmap: true

strategies: {}