config:
  max_open_trades: -1
  stake_currency: BTC
  stake_amount: 1
  tradable_balance_ratio: 0.99
  fiat_display_currency: USD
  timeframe: 5m
  dry_run: true
  cancel_open_orders_on_exit: false
  unfilledtimeout:
  download_trades: false
  exchange:
    name: kraken
    key: ''
    secret: ''
    ccxt_config:
      enableRateLimit: true
      rateLimit: 3100
    ccxt_async_config:
      enableRateLimit: true
      rateLimit: 3100
    pair_whitelist: []
    pair_blacklist: []
  pairlists:
  - method: StaticPairList
  edge:
    enabled: false
  telegram:
    enabled: false
    token: ''
    chat_id: ''
  api_server:
    enabled: false
    listen_ip_address: 0.0.0.0
    listen_port: 8080
    username: admin
    password: secret123
  bot_name: freqtrade
  initial_state: running
  force_entry_enable: false
  internals:
    process_throttle_secs: 5

image:
  image: freqtradeorg/freqtrade
  tag: latest

backtesting:
  enabled: false
  download_data: true
  timerange:
  timeframes: 5m
  strategy_list: SampleStrategy
  fee:
  pvc_size: 1Gi
  results:
    enable_export: true
    reader_enabled: true
    pvc_size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256M
    limits:
      cpu: 100m
      memory: 256M

bot:
  enabled: false
  strategy_name: SampleStrategy
  pvc_size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256M
    limits:
      cpu: 100m
      memory: 256M
  volumeMounts: []
  volumes: []

ingress:
  enabled: false
  annotations: {}
  apiVersion: "networking.k8s.io/v1"
  className: ""
  host: "localhost"
  tls:
    enabled: false
    secretName: "freqtrade-tls"

create_config_configmap: true
create_strategies_configmap: true

strategies: {}